### ISSUE TITLE
./contact.sh: línea 47: jq: orden no encontrada

### ISSUE THREAD

**Issue by Oxicode** [EdOverflow/contact.sh#2]
![image](https://user-images.githubusercontent.com/1320709/34569682-7b9b8f92-f137-11e7-81d1-5e4a901273be.png)

**Comment by EdOverflow** [comment]
Debes instalar `jq`. <sup>[[1]](https://stedolan.github.io/jq/download/)</sup>

```
sudo apt-get install jq
```
