### ISSUE TITLE
[Suggestion] Search both @ and www

### ISSUE THREAD

**Issue by BeanBagKing** [EdOverflow/contact.sh#6]
When searching for security.txt (and possibly other options), it would be good for the tool to search both domain.example and www.domain.example.

Using Google for an example, I noticed that "contact.sh -d google.com" did not return a security.txt. I found that this is because the file actually exists under www. In other words, "contact.sh -d www.google.com" works and returns the security.txt file.

On the other hand, if I do "contact.sh -d nullsec.us" on my site, it -will- return a security.txt. However, as I have all www. requests redirected to nullsec.us, a request for "contact.sh -d www.nullsec.us" does not return any information.

As the primary use of this tool is to try to find contact information, I believe it may be best for it to query both the naked domain as well as www.

**Comment by EdOverflow** [comment]
Good thinking, @BeanBagKing! I will push an update in a bit that checks `www.` too.

**Comment by BeanBagKing** [comment]
I would suggest checking the naked domain as well, if www is removed. I just updated, so with the newest code, try "contact.sh -d www.nullsec.us" and "contact.sh -d nullsec.us". The first does not return results (i.e. the situation is reversed).

**Comment by EdOverflow** [comment]
Oh, I like your solution better! Would you be willing to submit a pull request with your changes?

**Comment by BeanBagKing** [comment]
I DID IT! This is my first pull request by the way, and my god did that process make me feel like an idiot. I did it from the wrong direction several times before finding a video that properly walked me through it. I believe it has been correctly submitted though.

**Comment by EdOverflow** [comment]
Oh, wow! Congratulations and fantastic work, @BeanBagKing. :tada: Thank you very much for your help. If you are interested in learning more about GIT, I highly recommend https://try.github.io/levels/1/challenges/1 and https://www.youtube.com/watch?v=1h9_cB9mPT8&list=PLqGj3iMvMa4LFz8DZ0t-89twnelpT4Ilw.
