### ISSUE TITLE
mailtester.com false negatives?

### ISSUE THREAD

**Issue by 0xmilan** [EdOverflow/contact.sh#8]
Hi,

I don't think I ever got a positive results for the RFC 2142 check.
Could it be possible that mailtester.com is blocked on major email service providers?

As an example, run contact.sh on arduino.cc:
`./contact.sh -d arduino.cc`
![contact sh](https://user-images.githubusercontent.com/9085465/71756044-d9f1f280-2e8d-11ea-9ab5-98f4edeff7ed.png)

The tool finds security.txt which states that the security@ address should be used.
Still, the mailtester.com check says that security@arduino.cc is not valid.

Manually checking the email address on mailtester.com gives the following result:
![mailtester](https://user-images.githubusercontent.com/9085465/71756159-7916ea00-2e8e-11ea-8fed-d1a31b36ff2d.png)

"The user you are trying to contact is receiving mail at a rate that prevents additional messages from being delivered. Please resend your message at a later time. If the user is able to receive mail at that time, your message will be delivered. For more information, please visit https://support.google.com/..."

Sounds like Google is blocking this service from enumerating email addresses?
Sending an email to security@arduino.cc simply through gmail gives no errors.

**Comment by EdOverflow** [comment]
Yes, you are right. Some mail servers do not allow mailtester.com to validate mail addresses. As you pointed out, that is why you are seeing that error message. It works in some cases though as illustrated below:

![image](https://user-images.githubusercontent.com/18099289/71771717-44fc0180-2f40-11ea-98ff-c4ea92883427.png)

Please let me know if you experience any issues with the example above.

**Comment by 0xmilan** [comment]
I get the same results as your screenshot with manually checking at https://mailtester.com/index.php.
However, contact.sh has the following output:

```
[+] Doing an RFC 2142 check (security@amazon.com) 
 | Confidence level: ★ ★ ☆ 
security@amazon.com is not valid.
```

Running the curl command, this is the response:
```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>  
```
grep will never find "E-mail address is valid" in that :)


Change the URL to `https://mailtester.com/index.php` and you get a valid response:
```
curl --max-time 9 -X POST --silent https://mailtester.com/index.php -d "email=security@amazon.com" | grep "E-mail address is valid" 
<td bgcolor="#00DD00">E-mail address is valid</td></tr>
```

Edit:
Actually, testmail.php works too. The redirect was simply happening because of HTTP > HTTPS.

**Comment by milangfx** [comment]
Actually, testmail.php works too. The redirect was happening because of HTTP > HTTPS.

**Comment by EdOverflow** [comment]
Ah, looks like they may have introduced a redirect since I first wrote this tool. Thank you for pointing that out. Should be an easy fix. :)

**Comment by 0xmilan** [comment]
Yep, I just changed http to https for the mailtester.com request and it works fine with amazon.com.

**Comment by EdOverflow** [comment]
I think this issue should be fixed now. Thank you for taking the time to submit an issue ticket, @milangfx! :)

**Comment by 0xmilan** [comment]
Thanks for the fix :)
